### ISSUE TITLE
Descrever o componente de alta interatividade.

### ISSUE THREAD

**Issue by matheusgr** [samuelribeiroc/YouthTracker#1]
Podes descrever melhor como seria os componentes de alta interatividade?

como é o registro de uma série, talvez isso possa ser uma estrutura com visualização e notas dos episódios em uma caixa por temporada. E ter elementos de seleção e atualização que atualize o status de toda série, etc.

**Comment by samuelribeiroc** [comment]
Acho que marcar por temporada desviaria um pouco do intuito da aplicação, que serve mais para conhecer séries novas e não para registrar o progresso. Sobre os componentes de alta interatividade eu acho que ficaria para as tags de subgêneros, elas seriam responsáveis pela filtragem (não sei bem se é isso que se entende por componente de alta interatividade).
