### ISSUE TITLE
Filtrar séries por nota

### ISSUE THREAD

**Issue by caio-fm** [samuelribeiroc/YouthTracker#3]
Acho que uma funcionalidade de filtrar séries de forma que somente as que possuem nota acima de certo valor apareçam poderia ser interessante.

**Comment by samuelribeiroc** [comment]
É uma boa ideia! Vou deixar a issue aberta para quando eu conseguir implementar a funcionalidade de trazer a nota diretamente do site do IMDB implementar essa funcionalidade também.
